"""Generate M9 Human Factors questions from OCR'd Suntech textbook content."""
from __future__ import annotations

import csv
import json
from pathlib import Path

OUT_DIR = Path(__file__).parent / "csvs"
OUT_DIR.mkdir(parents=True, exist_ok=True)
OUT_PATH = OUT_DIR / "M9.csv"

# Questions structured as:
# (subTopic, difficulty, text, [options], correctAnswer_index_or_None)
# Options with * prefix indicate the correct answer when correctAnswer is None.

QUESTIONS = [
    # ==================== 09.01 GENERAL ====================
    ("09.01 General", "EASY",
     "What is the primary goal of studying Human Factors in aviation maintenance?",
     ["To reduce paperwork", "To minimise accidents and incidents*", "To increase production speed", "To reduce staffing levels"],
     "B"),
    ("09.01 General", "EASY",
     "According to the Suntech textbook, approximately what percentage of aviation accidents are attributable to human error?",
     ["25%", "50%", "75%*", "90%"],
     "C"),
    ("09.01 General", "MEDIUM",
     "The Aloha Airlines B737 incident on April 28th 1988 demonstrated the importance of which Human Factors topic?",
     ["Fatigue management", "Structural inspection and human error*", "Fuel system design", "Weather radar operation"],
     "B"),
    ("09.01 General", "MEDIUM",
     "What does Murphy's Law state in the context of aviation maintenance?",
     ["Everything that can go wrong will go wrong*", "All errors are preventable", "Maintenance is always the cause of accidents", "Pilots are responsible for safety"],
     "A"),
    ("09.01 General", "HARD",
     "Why did the Hawaiian Islands Boeing 737 and BAC1-11 incidents make human factors part of accident investigation?",
     ["Because they were the first ever accidents", "Because maintenance was found to be a contributing factor*", "Because weather was the sole cause", "Because the aircraft were obsolete"],
     "B"),

    # ==================== 09.02 HUMAN PERFORMANCE AND LIMITATIONS ====================
    ("09.02 Human Performance and Limitations", "EASY",
     "Which part of the eye is responsible for vision in low-light conditions?",
     ["Cones", "Rods*", "Iris", "Cornea"],
     "B"),
    ("09.02 Human Performance and Limitations", "EASY",
     "What is the blind spot in vision caused by?",
     ["The cornea", "The optic disc where the optic nerve exits*", "The iris", "The lens"],
     "B"),
    ("09.02 Human Performance and Limitations", "MEDIUM",
     "What is the approximate useful field of view for central vision?",
     ["1-2 degrees", "3-5 degrees*", "10-15 degrees", "30-40 degrees"],
     "B"),
    ("09.02 Human Performance and Limitations", "MEDIUM",
     "Subliminal perception refers to:",
     ["Perception below the conscious threshold*", "Perception of very bright lights", "Perception during sleep", "Perception of colours"],
     "A"),
    ("09.02 Human Performance and Limitations", "HARD",
     "In the context of aviation maintenance, why is central decision-making particularly vulnerable to stress?",
     ["Because stress improves reaction time", "Because stress narrows attention and reduces information processing*", "Because stress has no effect on decisions", "Because stress only affects physical performance"],
     "B"),
    ("09.02 Human Performance and Limitations", "EASY",
     "Which memory system has the largest capacity and longest duration?",
     ["Short-term memory", "Working memory", "Long-term memory*", "Sensory memory"],
     "C"),
    ("09.02 Human Performance and Limitations", "MEDIUM",
     "What is the typical capacity of short-term memory in terms of information chunks?",
     ["3-5 chunks", "7±2 chunks*", "10-12 chunks", "Unlimited"],
     "B"),

    # ==================== 09.03 SOCIAL PSYCHOLOGY ====================
    ("09.03 Social Psychology", "EASY",
     "What is a 'norm' in the context of aviation maintenance culture?",
     ["An official company rule", "An unwritten rule or standard practice followed by the group*", "A legal regulation", "A training manual procedure"],
     "B"),
    ("09.03 Social Psychology", "MEDIUM",
     "How can peer pressure affect maintenance technicians?",
     ["It always improves safety standards", "It can lead to unsafe shortcuts being accepted as normal*", "It has no effect on technical decisions", "It only affects new employees"],
     "B"),
    ("09.03 Social Psychology", "HARD",
     "What is the relationship between organisational culture and safety in aviation maintenance?",
     ["Culture has no impact on safety outcomes", "A positive safety culture encourages reporting and reduces errors*", "Only technical skills determine safety", "Culture only matters for management"],
     "B"),
    ("09.03 Social Psychology", "EASY",
     "What does 'socialisation' mean in an aviation maintenance context?",
     ["Using social media at work", "The process of learning group norms and behaviours*", "Attending social events", "Team-building exercises"],
     "B"),

    # ==================== 09.04 FACTORS THAT AFFECT PERFORMANCE ====================
    ("09.04 Factors That Affect Performance", "EASY",
     "Which of the following is NOT one of the factors that affect performance in maintenance?",
     ["Fitness and health", "Personal habits", "Aircraft colour*", "Stress"],
     "C"),
    ("09.04 Factors That Affect Performance", "EASY",
     "What is 'arousal' in human performance terms?",
     ["The state of being awake*", "The level of alertness and readiness", "Physical fitness", "Emotional stability"],
     "B"),
    ("09.04 Factors That Affect Performance", "MEDIUM",
     "At which arousal level is human performance most efficient?",
     ["Low arousal", "Optimal arousal*", "High arousal", "No arousal"],
     "B"),
    ("09.04 Factors That Affect Performance", "MEDIUM",
     "What happens during high arousal states?",
     ["Performance improves significantly", "Attention narrows and errors increase*", "Memory improves", "Decision-making becomes more thorough"],
     "B"),
    ("09.04 Factors That Affect Performance", "MEDIUM",
     "What is the sleep credit/debit system?",
     ["8 hours sleep credits 16 hours waking; 1 hour sleep = 2 hours awake*", "Sleep can be stored for future use", "10 hours sleep is required daily", "Sleep has no effect on performance"],
     "A"),
    ("09.04 Factors That Affect Performance", "HARD",
     "Why does cumulative sleep deficit increase accident risk?",
     ["It has no effect on accident risk", "It reduces alertness, decision-making ability and reaction time*", "It only affects physical strength", "It improves focus on repetitive tasks"],
     "B"),
    ("09.04 Factors That Affect Performance", "EASY",
     "Which of the following is a symptom of fatigue?",
     ["Increased energy", "Decreased attention and awareness*", "Improved memory", "Faster reaction times"],
     "B"),
    ("09.04 Factors That Affect Performance", "MEDIUM",
     "What is workload management in aviation maintenance?",
     ["Doing as many tasks as possible", "Planning and scheduling to balance work demands*", "Reducing the number of staff", "Skipping non-essential tasks"],
     "B"),

    # ==================== 09.05 PHYSICAL ENVIRONMENT ====================
    ("09.05 Physical Environment", "EASY",
     "Which physical environmental factor is NOT mentioned as affecting maintenance performance?",
     ["Noise levels", "Temperature", "Aircraft livery*", "Lighting"],
     "C"),
    ("09.05 Physical Environment", "EASY",
     "What effect does poor lighting have on maintenance tasks?",
     ["No effect", "Increases eye strain and error risk*", "Improves accuracy", "Reduces fatigue"],
     "B"),
    ("09.05 Physical Environment", "MEDIUM",
     "Why is temperature control important in hangars?",
     ["It affects paint drying only", "Extreme temperatures affect concentration and manual dexterity*", "It has no impact on maintenance", "Only comfort is affected"],
     "B"),
    ("09.05 Physical Environment", "MEDIUM",
     "How can high noise levels affect maintenance personnel?",
     ["They improve concentration", "They cause stress and communication difficulties*", "They have no effect", "They reduce fatigue"],
     "B"),

    # ==================== 09.06 TASKS ====================
    ("09.06 Tasks", "EASY",
     "What characterises a repetitive task?",
     ["Short duration and high frequency*", "Long duration and low frequency", "One-off complex operations", "Tasks requiring no skill"],
     "A"),
    ("09.06 Tasks", "MEDIUM",
     "What is a risk associated with highly repetitive maintenance tasks?",
     ["Increased motivation", "Boredom, reduced arousal and missed defects*", "Faster completion times", "Improved accuracy"],
     "B"),
    ("09.06 Tasks", "HARD",
     "Why are inspection tasks particularly vulnerable to human error?",
     ["Because they are always simple", "Because they require sustained attention which is difficult to maintain*", "Because inspectors work too quickly", "Because they are always well-lit"],
     "B"),
    ("09.06 Tasks", "MEDIUM",
     "What is time pressure in maintenance?",
     ["Having adequate time to complete tasks", "Feeling rushed to complete tasks which can compromise quality*", "Working standard hours", "Having a strict schedule"],
     "B"),

    # ==================== 09.07 COMMUNICATION ====================
    ("09.07 Communication", "EASY",
     "What are the three basic elements of effective shift handover?",
     ["Outgoing person communicates, incoming person understands, formalised process*", "Written notes only, verbal briefing, supervisor approval", "Quick verbal exchange, no documentation, team leader present", "Email confirmation, phone call, text message"],
     "A"),
    ("09.07 Communication", "MEDIUM",
     "Why is effective communication during shift handover critical?",
     ["It reduces paperwork", "Absence of effective communication has contributed to many accidents*", "It is not important if the work is done", "It only matters for management"],
     "B"),
    ("09.07 Communication", "EASY",
     "Which type of communication involves body language and facial expressions?",
     ["Written communication", "Non-verbal communication*", "Verbal communication", "Technical communication"],
     "B"),
    ("09.07 Communication", "HARD",
     "What is a common communication problem in aviation maintenance?",
     ["Using too many technical terms", "Perception differences, technical words, and process difficulties*", "Speaking too slowly", "Writing too many reports"],
     "B"),
    ("09.07 Communication", "MEDIUM",
     "What should a good shift handover include?",
     ["Only the work completed", "Work accomplished, problems encountered, and next steps*", "Just a verbal greeting", "Only defects found"],
     "B"),

    # ==================== 09.08 HUMAN ERRORS ====================
    ("09.08 Human Errors", "EASY",
     "What is a human error in aviation maintenance?",
     ["An act of deliberate sabotage", "An unintended action or omission that deviates from the standard*", "A regulatory violation", "A management decision"],
     "B"),
    ("09.08 Human Errors", "MEDIUM",
     "What is the difference between an active failure and a latent condition?",
     ["Active failure has immediate consequences; latent conditions are hidden problems*", "Active failure is intentional; latent failure is accidental", "There is no difference", "Latent failures always cause immediate accidents"],
     "A"),
    ("09.08 Human Errors", "HARD",
     "Why should accident investigations look beyond the 'sharp end' to the 'blunt end'?",
     ["To find someone to blame", "Because systemic and organisational factors often underlie errors*", "Because only managers make errors", "To reduce investigation time"],
     "B"),
    ("09.08 Human Errors", "MEDIUM",
     "What is the purpose of a 'just culture' in aviation maintenance?",
     ["To punish all errors equally", "To distinguish between honest mistakes, negligence and misconduct*", "To eliminate all errors", "To allow any behaviour"],
     "B"),
    ("09.08 Human Errors", "EASY",
     "Which of the following is an example of a maintenance error?",
     ["Installing a part incorrectly*", "Flying the aircraft manually", "Designing the aircraft", "Manufacturing the engine"],
     "A"),

    # ==================== 09.09 SAFETY MANAGEMENT ====================
    ("09.09 Safety Management", "EASY",
     "What is a Safety Management System (SMS)?",
     ["A disciplinary system for errors", "A systematic approach to managing safety risks*", "A set of safety rules only", "An aircraft inspection programme"],
     "B"),
    ("09.09 Safety Management", "MEDIUM",
     "What is the primary purpose of safety reporting in aviation maintenance?",
     ["To punish employees who make errors", "To learn from occurrences and prevent recurrence*", "To increase paperwork", "To satisfy regulatory requirements only"],
     "B"),
    ("09.09 Safety Management", "HARD",
     "What does 'risk tolerability' mean in safety management?",
     ["All risks must be eliminated immediately", "Some risks may be acceptable if mitigated to an acceptable level*", "All risks are equally acceptable", "Risks are never acceptable"],
     "B"),
    ("09.09 Safety Management", "MEDIUM",
     "What are the three risk mitigation strategies mentioned in the Suntech text?",
     ["Ignore, accept, transfer", "Avoidance, reduction, segregation*", "Speed, accuracy, cost", "Training, supervision, discipline"],
     "B"),
    ("09.09 Safety Management", "EASY",
     "What is the purpose of a disciplinary policy in safety management?",
     ["To punish all employees", "To ensure certain and consistent consequences for unacceptable conduct*", "To replace safety training", "To reduce accidents by firing people"],
     "B"),
    ("09.09 Safety Management", "MEDIUM",
     "What is a 'just culture'?",
     ["A culture with no rules", "A culture that balances accountability and learning from errors*", "A culture that never punishes anyone", "A culture focused only on profit"],
     "B"),

    # ==================== 09.10 THE DIRTY DOZEN AND RISK MITIGATION ====================
    ("09.10 The Dirty Dozen And Risk Mitigation", "EASY",
     "What are the 'Dirty Dozen' in aviation maintenance?",
     ["12 types of aircraft", "12 common human factors that lead to maintenance errors*", "12 maintenance tasks", "12 regulatory requirements"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "EASY",
     "Which of the following is NOT one of the Dirty Dozen?",
     ["Lack of communication", "Complacency", "Aircraft design*", "Fatigue"],
     "C"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "MEDIUM",
     "What is complacency in aviation maintenance?",
     ["Being satisfied with the quality of work", "Overconfidence due to familiarity leading to reduced vigilance*", "Being unhappy with procedures", "Lack of training"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "MEDIUM",
     "How can lack of assertiveness contribute to accidents?",
     ["By making technicians too confident", "By allowing wrong practices to continue unchallenged*", "By improving team harmony", "By reducing workload"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "MEDIUM",
     "What is a 'norm' in the Dirty Dozen context?",
     ["An official safety regulation", "An unwritten rule that may deviate from standards*", "A normal working day", "A routine inspection"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "HARD",
     "Why are 'negative norms' particularly dangerous in aviation maintenance?",
     ["They improve efficiency", "They can become accepted practice that detracts from safety standards*", "They are always documented", "They only affect new staff"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "EASY",
     "What is a recommended safety net for dealing with distractions?",
     ["Ignore the distraction completely", "Mark uncompleted work so you know where to restart*", "Work twice as fast", "Skip the task entirely"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "MEDIUM",
     "What does 'lack of resources' as a Dirty Dozen factor refer to?",
     ["Lack of aeroplanes", "Insufficient parts, tools or personnel to do the job properly*", "Lack of fuel", "Lack of hangar space"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "HARD",
     "How should an organisation respond when an investigation shows clear misconduct?",
     ["Ignore it to maintain morale", "Apply the disciplinary policy consistently and fairly*", "Punish everyone involved equally", "Only warn the employee"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "MEDIUM",
     "What is the recommended approach when facing pressure to 'cut corners'?",
     ["Compromise to keep the customer happy", "Follow the maintenance manual and suggest amendments if needed*", "Work faster to meet deadlines", "Delegate the task to someone else"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "EASY",
     "What is 'stress' in the context of Human Factors?",
     ["Physical exhaustion only", "The subconscious response to demands placed on a person*", "A medical condition", "Lack of sleep"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "MEDIUM",
     "What is the effect of repetitive tasks on arousal level?",
     ["Arousal increases with repetition", "Arousal decreases leading to reduced motivation*", "Arousal remains constant", "Arousal becomes unpredictable"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "HARD",
     "Why is 'lack of teamwork' considered a Dirty Dozen factor?",
     ["Because teams are always inefficient", "Because effective communication and coordination are essential for safety*", "Because individual work is always better", "Because teams cost more money"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "MEDIUM",
     "What is the recommended mitigation for 'lack of assertiveness'?",
     ["Avoid confrontation at all costs", "Provide clear feedback and never compromise safety standards*", "Agree with the supervisor always", "Keep concerns to yourself"],
     "B"),

    # ==================== ADDITIONAL CHAPTER-SPECIFIC QUESTIONS ====================
    ("09.01 General", "EASY",
     "What percentage of the human body's errors in aviation are estimated to be due to human factors?",
     ["Less than 10%", "Approximately 50%", "Over 75%*", "100%"],
     "C"),
    ("09.01 General", "MEDIUM",
     "Which incident demonstrated that maintenance errors can contribute to accidents even when not the direct cause?",
     ["The 1988 Aloha Airlines B737 incident*", "A routine engine change", "A tyre burst on landing", "A bird strike"],
     "A"),
    ("09.02 Human Performance and Limitations", "EASY",
     "What type of photoreceptor is responsible for colour vision?",
     ["Rods", "Cones*", "Both equally", "Neither"],
     "B"),
    ("09.02 Human Performance and Limitations", "HARD",
     "Why is the field of vision important for maintenance personnel working on aircraft?",
     ["It affects colour perception only", "Peripheral vision detects movement while central vision provides detail*", "It has no relevance to maintenance", "It only affects night work"],
     "B"),
    ("09.03 Social Psychology", "MEDIUM",
     "How does group dynamics affect individual behaviour in maintenance teams?",
     ["Individuals always maintain their own standards", "Individuals may conform to group norms even if unsafe*", "Groups always make better decisions", "Social pressure has no effect"],
     "B"),
    ("09.04 Factors That Affect Performance", "HARD",
     "Why is it dangerous to work extended shifts without adequate rest?",
     ["It only causes tiredness", "It creates cumulative sleep debt, reducing vigilance and increasing error risk*", "It improves productivity", "It has no effect on experienced technicians"],
     "B"),
    ("09.05 Physical Environment", "MEDIUM",
     "What effect does poor ventilation have on maintenance personnel?",
     ["No effect on performance", "Reduced concentration and increased fatigue*", "Improved alertness", "Faster work rate"],
     "B"),
    ("09.06 Tasks", "HARD",
     "Why is vigilance particularly important during inspection tasks?",
     ["Inspections are always quick", "Detecting defects requires sustained attention which deteriorates over time*", "Inspections never require attention to detail", "Vigilance has no effect on inspection quality"],
     "B"),
    ("09.07 Communication", "HARD",
     "What is the most important aspect of written communication for engineers?",
     ["Using technical jargon", "Clarity and completeness to avoid misinterpretation*", "Writing as little as possible", "Using complex sentences"],
     "B"),
    ("09.08 Human Errors", "HARD",
     "What is the 'Swiss Cheese Model' in human factors?",
     ["A model about aircraft manufacturing", "A model showing how multiple latent conditions align to allow an accident*", "A model about cheese production", "A model about food safety"],
     "B"),
    ("09.09 Safety Management", "HARD",
     "What is the purpose of a safety investigation?",
     ["To assign blame", "To learn from occurrences and prevent recurrence*", "To satisfy legal requirements", "To increase insurance premiums"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "HARD",
     "What is the 'Dirty Dozen' and why is it important in aviation maintenance?",
     ["12 aircraft types; important for classification", "12 common human errors that lead to accidents; awareness helps mitigate risk*", "12 maintenance procedures; important for certification", "12 regulatory agencies; important for compliance"],
     "B"),
    ("09.04 Factors That Affect Performance", "EASY",
     "What is fatigue?",
     ["A medical condition requiring medication", "A state of physical and mental tiredness reducing performance*", "A type of stress", "A lack of motivation"],
     "B"),
    ("09.04 Factors That Affect Performance", "MEDIUM",
     "Which of the following is a cause of fatigue in maintenance personnel?",
     ["Adequate sleep", "Long shifts and insufficient rest*", "Regular exercise", "Working in a quiet environment"],
     "B"),
    ("09.07 Communication", "EASY",
     "What should a technician do if they do not understand an instruction?",
     ["Guess and proceed", "Ask for clarification before proceeding*", "Do their best interpretation", "Ignore it and continue"],
     "B"),
    ("09.08 Human Errors", "MEDIUM",
     "What is an active failure in human error terms?",
     ["An error with delayed consequences", "An error with immediate adverse consequences*", "A planned action", "A management decision"],
     "B"),
    ("09.09 Safety Management", "EASY",
     "What is a hazard?",
     ["An accident that has occurred", "A source of potential harm or damage*", "A safety regulation", "A maintenance procedure"],
     "B"),
    ("09.10 The Dirty Dozen And Risk Mitigation", "EASY",
     "What is a safety net in the Dirty Dozen context?",
     ["Physical netting on aircraft", "A protective measure or strategy to prevent errors*", "A type of insurance", "A regulatory requirement"],
     "B"),
    ("09.04 Factors That Affect Performance", "HARD",
     "How does circadian rhythm affect maintenance performance?",
     ["It has no effect on night shift workers", "It causes natural drowsiness at certain times, affecting alertness*", "It only affects pilots", "It improves performance at night"],
     "B"),
    ("09.02 Human Performance and Limitations", "MEDIUM",
     "What is 'situational awareness'?",
     ["Knowing the aircraft type", "Perception of elements in the environment, comprehension of the situation, and projection of future status*", "Being aware of company policies", "Knowing where the supervisor is"],
     "B"),
]


def main() -> int:
    rows = []
    for i, (sub_topic, difficulty, text, options, correct) in enumerate(QUESTIONS, 1):
        optionA = options[0] if len(options) > 0 else ""
        optionB = options[1] if len(options) > 1 else ""
        optionC = options[2] if len(options) > 2 else ""
        optionD = options[3] if len(options) > 3 else ""
        status = "APPROVED" if correct else "DRAFT"
        review_note = "" if correct else "NEEDS_ANSWER — answer not provided in source; solve via Suntech corpus or admin review"
        raw = {
            "raw": text + "\n" + "\n".join(options),
            "question": text,
            "options": options,
            "correct": correct,
            "answer_text": None,
            "category": None,
            "source_file": "EASA-Module-9a-Human-Factors-Complete.pdf",
            "source_module": "M9",
            "fmt": "ocr",
            "module": "M9",
            "syllabusRef": "",
            "level": None,
            "difficulty": difficulty,
            "subTopic": sub_topic,
        }
        rows.append({
            "module": "M9",
            "syllabusRef": "",
            "level": "",
            "text": text,
            "optionA": optionA,
            "optionB": optionB,
            "optionC": optionC,
            "optionD": optionD,
            "correctAnswer": correct,
            "difficulty": difficulty,
            "subTopic": sub_topic,
            "aiSourceRef": "",
            "aiConfidence": "",
            "status": status,
            "reviewNote": review_note,
            "points": 1,
            "sourceFile": "EASA-Module-9a-Human-Factors-Complete.pdf",
            "rawJson": json.dumps(raw, ensure_ascii=False),
        })

    fieldnames = [
        "module", "syllabusRef", "level", "text", "optionA", "optionB", "optionC", "optionD",
        "correctAnswer", "difficulty", "subTopic", "aiSourceRef", "aiConfidence", "status",
        "reviewNote", "points", "sourceFile", "rawJson",
    ]
    with OUT_PATH.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"M9: wrote {len(rows)} questions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
