import sanitize from 'sanitize-html'

/**
 * Sanitize HTML content to prevent XSS attacks.
 * Allows standard formatting tags but strips scripts, event handlers, etc.
 */
export function sanitizeHtml(html: string): string {
  return sanitize(html, {
    allowedTags: [
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'p',
      'br',
      'hr',
      'ul',
      'ol',
      'li',
      'strong',
      'em',
      'b',
      'i',
      'u',
      's',
      'del',
      'ins',
      'a',
      'img',
      'blockquote',
      'pre',
      'code',
      'table',
      'thead',
      'tbody',
      'tr',
      'th',
      'td',
      'div',
      'span',
      'sub',
      'sup',
      'figure',
      'figcaption',
      'video',
      'source',
      'iframe',
      'audio',
    ],
    allowedAttributes: {
      '*': ['class'],
      a: ['href', 'target', 'rel'],
      img: ['src', 'alt', 'title', 'width', 'height'],
      table: ['colspan', 'rowspan'],
      td: ['colspan', 'rowspan'],
      th: ['colspan', 'rowspan'],
      iframe: ['src', 'allowfullscreen', 'frameborder'],
      video: ['src', 'controls', 'width', 'height'],
      audio: ['src', 'controls'],
      source: ['src', 'type'],
    },
    allowedSchemes: ['http', 'https', 'mailto', 'tel', 'data'],
  })
}
