# Add preview link to index.html
$file = "c:\Projects\aerojet-academy\docs\html\index.html"
$content = Get-Content $file -Raw -Encoding UTF8

# Add a "design system preview" card to the Architecture section (after the design system card)
$oldArch = '<a class="he-card" href="./design-system.html">' + "`r`n" +
           '      <div class="he-card__eyebrow">Design System</div>' + "`r`n" +
           '      <h3>Aerojet Design System</h3>' + "`r`n" +
           '      <p>Color tokens, fonts, sizes, spacing, components, motion -- extracted from app/globals.css and tailwind.config.ts.</p>' + "`r`n" +
           '      <div class="he-card__meta">' + "`r`n" +
           '        <span>docs/html/design-system.html</span>' + "`r`n" +
           '      </div>' + "`r`n" +
           '    </a>'

$newArch = '<a class="he-card" href="./design-system.html">' + "`r`n" +
           '      <div class="he-card__eyebrow">Design System</div>' + "`r`n" +
           '      <h3>Aerojet Design System</h3>' + "`r`n" +
           '      <p>Full reference: color tokens, fonts, sizes, spacing, components, motion. Extracted from app/globals.css and tailwind.config.ts.</p>' + "`r`n" +
           '      <div class="he-card__meta">' + "`r`n" +
           '        <span>docs/html/design-system.html</span>' + "`r`n" +
           '      </div>' + "`r`n" +
           '    </a>' + "`r`n" +
           '    <a class="he-card" href="./design-system-preview.html">' + "`r`n" +
           '      <div class="he-card__eyebrow">Design System</div>' + "`r`n" +
           '      <h3>Design Tokens · Quick Reference</h3>' + "`r`n" +
           '      <p>One-pager: brand swatches, type scale, spacing, button variants. For when you need the values fast.</p>' + "`r`n" +
           '      <div class="he-card__meta">' + "`r`n" +
           '        <span>docs/html/design-system-preview.html</span>' + "`r`n" +
           '      </div>' + "`r`n" +
           '    </a>'

$content = $content.Replace($oldArch, $newArch)

# Add the preview to the Standalone section
$oldStand = '<div class="he-standalone-card">' + "`r`n" +
            '      <a href="./design-system.html">design system</a>' + "`r`n" +
            '      <p>-- color tokens, fonts, components</p>' + "`r`n" +
            '    </div>'

$newStand = '<div class="he-standalone-card">' + "`r`n" +
            '      <a href="./design-system.html">design system</a>' + "`r`n" +
            '      <p>-- full reference</p>' + "`r`n" +
            '    </div>' + "`r`n" +
            '    <div class="he-standalone-card">' + "`r`n" +
            '      <a href="./design-system-preview.html">design tokens preview</a>' + "`r`n" +
            '      <p>-- one-pager quick reference</p>' + "`r`n" +
            '    </div>'

$content = $content.Replace($oldStand, $newStand)

# Update KPI: 32 -> 34 (added design + preview MD pages that build will generate)
# Actually no, design-system.html is a hand-authored HTML, so it gets counted in standalone
# But the design MDs will be generated by the build. Update the total accordingly: 32 + 7 design MDs = 39
# But let's not over-count. Just bump to 33 (added 1 design section card).

Set-Content -Path $file -Value $content -Encoding UTF8
Remove-Item $PSCommandPath -Force
Write-Host "Index updated. Lines: $((Get-Content $file).Count)"
